services: docker

before_install:
  - docker -v
  - git clone https://github.com/bitdust-io/tests.git tests_e2e

  - mkdir -p tests_e2e/src/bitdust
  - rsync -rR . tests_e2e/src/bitdust
  - cd tests_e2e

script:
  - make -j2 all
  - make test_1
  - make test_2
  #- docker-compose exec test sh -c "pytest tests/test_ss/ -v -s"
  #- docker-compose exec test sh -c "pytest tests/test_upload_file/ -v -s"
  - make -j2 clean_all
